### ISSUE TITLE
Update "Getting started" in project wiki

### ISSUE THREAD

**Issue by jocelynmutso** [the-wrench-io/thena-parent#6]
The main README has a link to the wiki for "Getting started", but it doesn't tell you anything about how to set up the project.

Add a page in the wiki to include "Getting started" instructions on how to get the project set up and running locally.

**Comment by admirkrilasevic** [comment]
"Getting started" wiki page created and available [here](https://github.com/the-wrench-io/thena-parent/wiki/Getting-Started)
